// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v3.21.12
// source: accounts.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { CallContext, CallOptions } from "nice-grpc-common";
import { Empty } from "./google/protobuf/empty";

export const protobufPackage = "config.accounts";

export interface CurrentUserProfileUpdateCurrentUserProfileRequest {
  bio: string;
  avatarUrl: string;
}

export interface CurrentUserUpdateCurrentUserRequest {
  email: string;
  firstName: string;
  lastName: string;
}

export interface UserProfileResponse {
  id?: number | undefined;
  user?: UserResponse | undefined;
  bio?: string | undefined;
  avatarUrl?: string | undefined;
  isActive?: boolean | undefined;
}

export interface UserResponse {
  id?: number | undefined;
  username: string;
  email?: string | undefined;
  firstName?: string | undefined;
  lastName?: string | undefined;
}

function createBaseCurrentUserProfileUpdateCurrentUserProfileRequest(): CurrentUserProfileUpdateCurrentUserProfileRequest {
  return { bio: "", avatarUrl: "" };
}

export const CurrentUserProfileUpdateCurrentUserProfileRequest: MessageFns<
  CurrentUserProfileUpdateCurrentUserProfileRequest
> = {
  encode(
    message: CurrentUserProfileUpdateCurrentUserProfileRequest,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.bio !== "") {
      writer.uint32(10).string(message.bio);
    }
    if (message.avatarUrl !== "") {
      writer.uint32(18).string(message.avatarUrl);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CurrentUserProfileUpdateCurrentUserProfileRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCurrentUserProfileUpdateCurrentUserProfileRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.bio = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.avatarUrl = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CurrentUserProfileUpdateCurrentUserProfileRequest {
    return {
      bio: isSet(object.bio) ? globalThis.String(object.bio) : "",
      avatarUrl: isSet(object.avatarUrl) ? globalThis.String(object.avatarUrl) : "",
    };
  },

  toJSON(message: CurrentUserProfileUpdateCurrentUserProfileRequest): unknown {
    const obj: any = {};
    if (message.bio !== "") {
      obj.bio = message.bio;
    }
    if (message.avatarUrl !== "") {
      obj.avatarUrl = message.avatarUrl;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CurrentUserProfileUpdateCurrentUserProfileRequest>, I>>(
    base?: I,
  ): CurrentUserProfileUpdateCurrentUserProfileRequest {
    return CurrentUserProfileUpdateCurrentUserProfileRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CurrentUserProfileUpdateCurrentUserProfileRequest>, I>>(
    object: I,
  ): CurrentUserProfileUpdateCurrentUserProfileRequest {
    const message = createBaseCurrentUserProfileUpdateCurrentUserProfileRequest();
    message.bio = object.bio ?? "";
    message.avatarUrl = object.avatarUrl ?? "";
    return message;
  },
};

function createBaseCurrentUserUpdateCurrentUserRequest(): CurrentUserUpdateCurrentUserRequest {
  return { email: "", firstName: "", lastName: "" };
}

export const CurrentUserUpdateCurrentUserRequest: MessageFns<CurrentUserUpdateCurrentUserRequest> = {
  encode(message: CurrentUserUpdateCurrentUserRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.email !== "") {
      writer.uint32(10).string(message.email);
    }
    if (message.firstName !== "") {
      writer.uint32(18).string(message.firstName);
    }
    if (message.lastName !== "") {
      writer.uint32(26).string(message.lastName);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CurrentUserUpdateCurrentUserRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCurrentUserUpdateCurrentUserRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.email = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.firstName = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.lastName = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CurrentUserUpdateCurrentUserRequest {
    return {
      email: isSet(object.email) ? globalThis.String(object.email) : "",
      firstName: isSet(object.firstName) ? globalThis.String(object.firstName) : "",
      lastName: isSet(object.lastName) ? globalThis.String(object.lastName) : "",
    };
  },

  toJSON(message: CurrentUserUpdateCurrentUserRequest): unknown {
    const obj: any = {};
    if (message.email !== "") {
      obj.email = message.email;
    }
    if (message.firstName !== "") {
      obj.firstName = message.firstName;
    }
    if (message.lastName !== "") {
      obj.lastName = message.lastName;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CurrentUserUpdateCurrentUserRequest>, I>>(
    base?: I,
  ): CurrentUserUpdateCurrentUserRequest {
    return CurrentUserUpdateCurrentUserRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CurrentUserUpdateCurrentUserRequest>, I>>(
    object: I,
  ): CurrentUserUpdateCurrentUserRequest {
    const message = createBaseCurrentUserUpdateCurrentUserRequest();
    message.email = object.email ?? "";
    message.firstName = object.firstName ?? "";
    message.lastName = object.lastName ?? "";
    return message;
  },
};

function createBaseUserProfileResponse(): UserProfileResponse {
  return { id: undefined, user: undefined, bio: undefined, avatarUrl: undefined, isActive: undefined };
}

export const UserProfileResponse: MessageFns<UserProfileResponse> = {
  encode(message: UserProfileResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== undefined) {
      writer.uint32(8).int64(message.id);
    }
    if (message.user !== undefined) {
      UserResponse.encode(message.user, writer.uint32(18).fork()).join();
    }
    if (message.bio !== undefined) {
      writer.uint32(26).string(message.bio);
    }
    if (message.avatarUrl !== undefined) {
      writer.uint32(34).string(message.avatarUrl);
    }
    if (message.isActive !== undefined) {
      writer.uint32(40).bool(message.isActive);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UserProfileResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserProfileResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.user = UserResponse.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.bio = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.avatarUrl = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.isActive = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UserProfileResponse {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : undefined,
      user: isSet(object.user) ? UserResponse.fromJSON(object.user) : undefined,
      bio: isSet(object.bio) ? globalThis.String(object.bio) : undefined,
      avatarUrl: isSet(object.avatarUrl) ? globalThis.String(object.avatarUrl) : undefined,
      isActive: isSet(object.isActive) ? globalThis.Boolean(object.isActive) : undefined,
    };
  },

  toJSON(message: UserProfileResponse): unknown {
    const obj: any = {};
    if (message.id !== undefined) {
      obj.id = Math.round(message.id);
    }
    if (message.user !== undefined) {
      obj.user = UserResponse.toJSON(message.user);
    }
    if (message.bio !== undefined) {
      obj.bio = message.bio;
    }
    if (message.avatarUrl !== undefined) {
      obj.avatarUrl = message.avatarUrl;
    }
    if (message.isActive !== undefined) {
      obj.isActive = message.isActive;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UserProfileResponse>, I>>(base?: I): UserProfileResponse {
    return UserProfileResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UserProfileResponse>, I>>(object: I): UserProfileResponse {
    const message = createBaseUserProfileResponse();
    message.id = object.id ?? undefined;
    message.user = (object.user !== undefined && object.user !== null)
      ? UserResponse.fromPartial(object.user)
      : undefined;
    message.bio = object.bio ?? undefined;
    message.avatarUrl = object.avatarUrl ?? undefined;
    message.isActive = object.isActive ?? undefined;
    return message;
  },
};

function createBaseUserResponse(): UserResponse {
  return { id: undefined, username: "", email: undefined, firstName: undefined, lastName: undefined };
}

export const UserResponse: MessageFns<UserResponse> = {
  encode(message: UserResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== undefined) {
      writer.uint32(8).int32(message.id);
    }
    if (message.username !== "") {
      writer.uint32(18).string(message.username);
    }
    if (message.email !== undefined) {
      writer.uint32(26).string(message.email);
    }
    if (message.firstName !== undefined) {
      writer.uint32(34).string(message.firstName);
    }
    if (message.lastName !== undefined) {
      writer.uint32(42).string(message.lastName);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UserResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.username = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.email = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.firstName = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.lastName = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UserResponse {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : undefined,
      username: isSet(object.username) ? globalThis.String(object.username) : "",
      email: isSet(object.email) ? globalThis.String(object.email) : undefined,
      firstName: isSet(object.firstName) ? globalThis.String(object.firstName) : undefined,
      lastName: isSet(object.lastName) ? globalThis.String(object.lastName) : undefined,
    };
  },

  toJSON(message: UserResponse): unknown {
    const obj: any = {};
    if (message.id !== undefined) {
      obj.id = Math.round(message.id);
    }
    if (message.username !== "") {
      obj.username = message.username;
    }
    if (message.email !== undefined) {
      obj.email = message.email;
    }
    if (message.firstName !== undefined) {
      obj.firstName = message.firstName;
    }
    if (message.lastName !== undefined) {
      obj.lastName = message.lastName;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UserResponse>, I>>(base?: I): UserResponse {
    return UserResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UserResponse>, I>>(object: I): UserResponse {
    const message = createBaseUserResponse();
    message.id = object.id ?? undefined;
    message.username = object.username ?? "";
    message.email = object.email ?? undefined;
    message.firstName = object.firstName ?? undefined;
    message.lastName = object.lastName ?? undefined;
    return message;
  },
};

export type CurrentUserControllerDefinition = typeof CurrentUserControllerDefinition;
export const CurrentUserControllerDefinition = {
  name: "CurrentUserController",
  fullName: "config.accounts.CurrentUserController",
  methods: {
    getCurrentUser: {
      name: "GetCurrentUser",
      requestType: Empty,
      requestStream: false,
      responseType: UserResponse,
      responseStream: false,
      options: {},
    },
    updateCurrentUser: {
      name: "UpdateCurrentUser",
      requestType: CurrentUserUpdateCurrentUserRequest,
      requestStream: false,
      responseType: UserResponse,
      responseStream: false,
      options: {},
    },
  },
} as const;

export interface CurrentUserControllerServiceImplementation<CallContextExt = {}> {
  getCurrentUser(request: Empty, context: CallContext & CallContextExt): Promise<DeepPartial<UserResponse>>;
  updateCurrentUser(
    request: CurrentUserUpdateCurrentUserRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<UserResponse>>;
}

export interface CurrentUserControllerClient<CallOptionsExt = {}> {
  getCurrentUser(request: DeepPartial<Empty>, options?: CallOptions & CallOptionsExt): Promise<UserResponse>;
  updateCurrentUser(
    request: DeepPartial<CurrentUserUpdateCurrentUserRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<UserResponse>;
}

export type CurrentUserProfileControllerDefinition = typeof CurrentUserProfileControllerDefinition;
export const CurrentUserProfileControllerDefinition = {
  name: "CurrentUserProfileController",
  fullName: "config.accounts.CurrentUserProfileController",
  methods: {
    getCurrentUserProfile: {
      name: "GetCurrentUserProfile",
      requestType: Empty,
      requestStream: false,
      responseType: UserProfileResponse,
      responseStream: false,
      options: {},
    },
    updateCurrentUserProfile: {
      name: "UpdateCurrentUserProfile",
      requestType: CurrentUserProfileUpdateCurrentUserProfileRequest,
      requestStream: false,
      responseType: UserProfileResponse,
      responseStream: false,
      options: {},
    },
  },
} as const;

export interface CurrentUserProfileControllerServiceImplementation<CallContextExt = {}> {
  getCurrentUserProfile(
    request: Empty,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<UserProfileResponse>>;
  updateCurrentUserProfile(
    request: CurrentUserProfileUpdateCurrentUserProfileRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<UserProfileResponse>>;
}

export interface CurrentUserProfileControllerClient<CallOptionsExt = {}> {
  getCurrentUserProfile(
    request: DeepPartial<Empty>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<UserProfileResponse>;
  updateCurrentUserProfile(
    request: DeepPartial<CurrentUserProfileUpdateCurrentUserProfileRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<UserProfileResponse>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
