// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v3.21.12
// source: documents.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { CallContext, CallOptions } from "nice-grpc-common";
import { Struct } from "./google/protobuf/struct";

export const protobufPackage = "config.documents";

export interface ContentBlockResponse {
  contentHash: string;
  jsxContent: string;
}

export interface DocumentListRequest {
}

export interface DocumentListResponse {
  results: DocumentResponse[];
}

export interface DocumentReadStreamPagesRequest {
  documentId: number;
}

export interface DocumentResponse {
  id?: number | undefined;
  title: string;
  source: number;
  reference: string;
  workdir: string;
  confPath: string;
  lastBuildAt?: string | undefined;
  globalContext?: { [key: string]: any } | undefined;
}

export interface DocumentRetrieveRequest {
  id: number;
}

export interface PageResponse {
  currentPageName: string;
  title: string;
  context?: { [key: string]: any } | undefined;
  sections: SectionResponse[];
}

export interface SectionResponse {
  title: string;
  sphinxId: string;
  hash: string;
  sourcePath: string;
  startLine: number;
  endLine: number;
  contentBlock?: ContentBlockResponse | undefined;
}

function createBaseContentBlockResponse(): ContentBlockResponse {
  return { contentHash: "", jsxContent: "" };
}

export const ContentBlockResponse: MessageFns<ContentBlockResponse> = {
  encode(message: ContentBlockResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.contentHash !== "") {
      writer.uint32(10).string(message.contentHash);
    }
    if (message.jsxContent !== "") {
      writer.uint32(18).string(message.jsxContent);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ContentBlockResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseContentBlockResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.contentHash = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.jsxContent = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ContentBlockResponse {
    return {
      contentHash: isSet(object.contentHash) ? globalThis.String(object.contentHash) : "",
      jsxContent: isSet(object.jsxContent) ? globalThis.String(object.jsxContent) : "",
    };
  },

  toJSON(message: ContentBlockResponse): unknown {
    const obj: any = {};
    if (message.contentHash !== "") {
      obj.contentHash = message.contentHash;
    }
    if (message.jsxContent !== "") {
      obj.jsxContent = message.jsxContent;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ContentBlockResponse>, I>>(base?: I): ContentBlockResponse {
    return ContentBlockResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ContentBlockResponse>, I>>(object: I): ContentBlockResponse {
    const message = createBaseContentBlockResponse();
    message.contentHash = object.contentHash ?? "";
    message.jsxContent = object.jsxContent ?? "";
    return message;
  },
};

function createBaseDocumentListRequest(): DocumentListRequest {
  return {};
}

export const DocumentListRequest: MessageFns<DocumentListRequest> = {
  encode(_: DocumentListRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DocumentListRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDocumentListRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): DocumentListRequest {
    return {};
  },

  toJSON(_: DocumentListRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<DocumentListRequest>, I>>(base?: I): DocumentListRequest {
    return DocumentListRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DocumentListRequest>, I>>(_: I): DocumentListRequest {
    const message = createBaseDocumentListRequest();
    return message;
  },
};

function createBaseDocumentListResponse(): DocumentListResponse {
  return { results: [] };
}

export const DocumentListResponse: MessageFns<DocumentListResponse> = {
  encode(message: DocumentListResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.results) {
      DocumentResponse.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DocumentListResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDocumentListResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.results.push(DocumentResponse.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DocumentListResponse {
    return {
      results: globalThis.Array.isArray(object?.results)
        ? object.results.map((e: any) => DocumentResponse.fromJSON(e))
        : [],
    };
  },

  toJSON(message: DocumentListResponse): unknown {
    const obj: any = {};
    if (message.results?.length) {
      obj.results = message.results.map((e) => DocumentResponse.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DocumentListResponse>, I>>(base?: I): DocumentListResponse {
    return DocumentListResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DocumentListResponse>, I>>(object: I): DocumentListResponse {
    const message = createBaseDocumentListResponse();
    message.results = object.results?.map((e) => DocumentResponse.fromPartial(e)) || [];
    return message;
  },
};

function createBaseDocumentReadStreamPagesRequest(): DocumentReadStreamPagesRequest {
  return { documentId: 0 };
}

export const DocumentReadStreamPagesRequest: MessageFns<DocumentReadStreamPagesRequest> = {
  encode(message: DocumentReadStreamPagesRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.documentId !== 0) {
      writer.uint32(8).int64(message.documentId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DocumentReadStreamPagesRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDocumentReadStreamPagesRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.documentId = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DocumentReadStreamPagesRequest {
    return { documentId: isSet(object.documentId) ? globalThis.Number(object.documentId) : 0 };
  },

  toJSON(message: DocumentReadStreamPagesRequest): unknown {
    const obj: any = {};
    if (message.documentId !== 0) {
      obj.documentId = Math.round(message.documentId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DocumentReadStreamPagesRequest>, I>>(base?: I): DocumentReadStreamPagesRequest {
    return DocumentReadStreamPagesRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DocumentReadStreamPagesRequest>, I>>(
    object: I,
  ): DocumentReadStreamPagesRequest {
    const message = createBaseDocumentReadStreamPagesRequest();
    message.documentId = object.documentId ?? 0;
    return message;
  },
};

function createBaseDocumentResponse(): DocumentResponse {
  return {
    id: undefined,
    title: "",
    source: 0,
    reference: "",
    workdir: "",
    confPath: "",
    lastBuildAt: undefined,
    globalContext: undefined,
  };
}

export const DocumentResponse: MessageFns<DocumentResponse> = {
  encode(message: DocumentResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== undefined) {
      writer.uint32(8).int64(message.id);
    }
    if (message.title !== "") {
      writer.uint32(18).string(message.title);
    }
    if (message.source !== 0) {
      writer.uint32(24).int64(message.source);
    }
    if (message.reference !== "") {
      writer.uint32(34).string(message.reference);
    }
    if (message.workdir !== "") {
      writer.uint32(42).string(message.workdir);
    }
    if (message.confPath !== "") {
      writer.uint32(50).string(message.confPath);
    }
    if (message.lastBuildAt !== undefined) {
      writer.uint32(58).string(message.lastBuildAt);
    }
    if (message.globalContext !== undefined) {
      Struct.encode(Struct.wrap(message.globalContext), writer.uint32(66).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DocumentResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDocumentResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.title = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.source = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.reference = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.workdir = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.confPath = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.lastBuildAt = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.globalContext = Struct.unwrap(Struct.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DocumentResponse {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : undefined,
      title: isSet(object.title) ? globalThis.String(object.title) : "",
      source: isSet(object.source) ? globalThis.Number(object.source) : 0,
      reference: isSet(object.reference) ? globalThis.String(object.reference) : "",
      workdir: isSet(object.workdir) ? globalThis.String(object.workdir) : "",
      confPath: isSet(object.confPath) ? globalThis.String(object.confPath) : "",
      lastBuildAt: isSet(object.lastBuildAt) ? globalThis.String(object.lastBuildAt) : undefined,
      globalContext: isObject(object.globalContext) ? object.globalContext : undefined,
    };
  },

  toJSON(message: DocumentResponse): unknown {
    const obj: any = {};
    if (message.id !== undefined) {
      obj.id = Math.round(message.id);
    }
    if (message.title !== "") {
      obj.title = message.title;
    }
    if (message.source !== 0) {
      obj.source = Math.round(message.source);
    }
    if (message.reference !== "") {
      obj.reference = message.reference;
    }
    if (message.workdir !== "") {
      obj.workdir = message.workdir;
    }
    if (message.confPath !== "") {
      obj.confPath = message.confPath;
    }
    if (message.lastBuildAt !== undefined) {
      obj.lastBuildAt = message.lastBuildAt;
    }
    if (message.globalContext !== undefined) {
      obj.globalContext = message.globalContext;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DocumentResponse>, I>>(base?: I): DocumentResponse {
    return DocumentResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DocumentResponse>, I>>(object: I): DocumentResponse {
    const message = createBaseDocumentResponse();
    message.id = object.id ?? undefined;
    message.title = object.title ?? "";
    message.source = object.source ?? 0;
    message.reference = object.reference ?? "";
    message.workdir = object.workdir ?? "";
    message.confPath = object.confPath ?? "";
    message.lastBuildAt = object.lastBuildAt ?? undefined;
    message.globalContext = object.globalContext ?? undefined;
    return message;
  },
};

function createBaseDocumentRetrieveRequest(): DocumentRetrieveRequest {
  return { id: 0 };
}

export const DocumentRetrieveRequest: MessageFns<DocumentRetrieveRequest> = {
  encode(message: DocumentRetrieveRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int64(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DocumentRetrieveRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDocumentRetrieveRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DocumentRetrieveRequest {
    return { id: isSet(object.id) ? globalThis.Number(object.id) : 0 };
  },

  toJSON(message: DocumentRetrieveRequest): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DocumentRetrieveRequest>, I>>(base?: I): DocumentRetrieveRequest {
    return DocumentRetrieveRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DocumentRetrieveRequest>, I>>(object: I): DocumentRetrieveRequest {
    const message = createBaseDocumentRetrieveRequest();
    message.id = object.id ?? 0;
    return message;
  },
};

function createBasePageResponse(): PageResponse {
  return { currentPageName: "", title: "", context: undefined, sections: [] };
}

export const PageResponse: MessageFns<PageResponse> = {
  encode(message: PageResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.currentPageName !== "") {
      writer.uint32(10).string(message.currentPageName);
    }
    if (message.title !== "") {
      writer.uint32(18).string(message.title);
    }
    if (message.context !== undefined) {
      Struct.encode(Struct.wrap(message.context), writer.uint32(26).fork()).join();
    }
    for (const v of message.sections) {
      SectionResponse.encode(v!, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PageResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePageResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.currentPageName = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.title = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.context = Struct.unwrap(Struct.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.sections.push(SectionResponse.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PageResponse {
    return {
      currentPageName: isSet(object.currentPageName) ? globalThis.String(object.currentPageName) : "",
      title: isSet(object.title) ? globalThis.String(object.title) : "",
      context: isObject(object.context) ? object.context : undefined,
      sections: globalThis.Array.isArray(object?.sections)
        ? object.sections.map((e: any) => SectionResponse.fromJSON(e))
        : [],
    };
  },

  toJSON(message: PageResponse): unknown {
    const obj: any = {};
    if (message.currentPageName !== "") {
      obj.currentPageName = message.currentPageName;
    }
    if (message.title !== "") {
      obj.title = message.title;
    }
    if (message.context !== undefined) {
      obj.context = message.context;
    }
    if (message.sections?.length) {
      obj.sections = message.sections.map((e) => SectionResponse.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PageResponse>, I>>(base?: I): PageResponse {
    return PageResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PageResponse>, I>>(object: I): PageResponse {
    const message = createBasePageResponse();
    message.currentPageName = object.currentPageName ?? "";
    message.title = object.title ?? "";
    message.context = object.context ?? undefined;
    message.sections = object.sections?.map((e) => SectionResponse.fromPartial(e)) || [];
    return message;
  },
};

function createBaseSectionResponse(): SectionResponse {
  return { title: "", sphinxId: "", hash: "", sourcePath: "", startLine: 0, endLine: 0, contentBlock: undefined };
}

export const SectionResponse: MessageFns<SectionResponse> = {
  encode(message: SectionResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.title !== "") {
      writer.uint32(10).string(message.title);
    }
    if (message.sphinxId !== "") {
      writer.uint32(18).string(message.sphinxId);
    }
    if (message.hash !== "") {
      writer.uint32(26).string(message.hash);
    }
    if (message.sourcePath !== "") {
      writer.uint32(34).string(message.sourcePath);
    }
    if (message.startLine !== 0) {
      writer.uint32(40).int32(message.startLine);
    }
    if (message.endLine !== 0) {
      writer.uint32(48).int32(message.endLine);
    }
    if (message.contentBlock !== undefined) {
      ContentBlockResponse.encode(message.contentBlock, writer.uint32(58).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SectionResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSectionResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.title = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.sphinxId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.hash = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.sourcePath = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.startLine = reader.int32();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.endLine = reader.int32();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.contentBlock = ContentBlockResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SectionResponse {
    return {
      title: isSet(object.title) ? globalThis.String(object.title) : "",
      sphinxId: isSet(object.sphinxId) ? globalThis.String(object.sphinxId) : "",
      hash: isSet(object.hash) ? globalThis.String(object.hash) : "",
      sourcePath: isSet(object.sourcePath) ? globalThis.String(object.sourcePath) : "",
      startLine: isSet(object.startLine) ? globalThis.Number(object.startLine) : 0,
      endLine: isSet(object.endLine) ? globalThis.Number(object.endLine) : 0,
      contentBlock: isSet(object.contentBlock) ? ContentBlockResponse.fromJSON(object.contentBlock) : undefined,
    };
  },

  toJSON(message: SectionResponse): unknown {
    const obj: any = {};
    if (message.title !== "") {
      obj.title = message.title;
    }
    if (message.sphinxId !== "") {
      obj.sphinxId = message.sphinxId;
    }
    if (message.hash !== "") {
      obj.hash = message.hash;
    }
    if (message.sourcePath !== "") {
      obj.sourcePath = message.sourcePath;
    }
    if (message.startLine !== 0) {
      obj.startLine = Math.round(message.startLine);
    }
    if (message.endLine !== 0) {
      obj.endLine = Math.round(message.endLine);
    }
    if (message.contentBlock !== undefined) {
      obj.contentBlock = ContentBlockResponse.toJSON(message.contentBlock);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SectionResponse>, I>>(base?: I): SectionResponse {
    return SectionResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SectionResponse>, I>>(object: I): SectionResponse {
    const message = createBaseSectionResponse();
    message.title = object.title ?? "";
    message.sphinxId = object.sphinxId ?? "";
    message.hash = object.hash ?? "";
    message.sourcePath = object.sourcePath ?? "";
    message.startLine = object.startLine ?? 0;
    message.endLine = object.endLine ?? 0;
    message.contentBlock = (object.contentBlock !== undefined && object.contentBlock !== null)
      ? ContentBlockResponse.fromPartial(object.contentBlock)
      : undefined;
    return message;
  },
};

export type DocumentReadControllerDefinition = typeof DocumentReadControllerDefinition;
export const DocumentReadControllerDefinition = {
  name: "DocumentReadController",
  fullName: "config.documents.DocumentReadController",
  methods: {
    list: {
      name: "List",
      requestType: DocumentListRequest,
      requestStream: false,
      responseType: DocumentListResponse,
      responseStream: false,
      options: {},
    },
    retrieve: {
      name: "Retrieve",
      requestType: DocumentRetrieveRequest,
      requestStream: false,
      responseType: DocumentResponse,
      responseStream: false,
      options: {},
    },
    streamPages: {
      name: "StreamPages",
      requestType: DocumentReadStreamPagesRequest,
      requestStream: false,
      responseType: PageResponse,
      responseStream: true,
      options: {},
    },
  },
} as const;

export interface DocumentReadControllerServiceImplementation<CallContextExt = {}> {
  list(request: DocumentListRequest, context: CallContext & CallContextExt): Promise<DeepPartial<DocumentListResponse>>;
  retrieve(
    request: DocumentRetrieveRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<DocumentResponse>>;
  streamPages(
    request: DocumentReadStreamPagesRequest,
    context: CallContext & CallContextExt,
  ): ServerStreamingMethodResult<DeepPartial<PageResponse>>;
}

export interface DocumentReadControllerClient<CallOptionsExt = {}> {
  list(
    request: DeepPartial<DocumentListRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<DocumentListResponse>;
  retrieve(
    request: DeepPartial<DocumentRetrieveRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<DocumentResponse>;
  streamPages(
    request: DeepPartial<DocumentReadStreamPagesRequest>,
    options?: CallOptions & CallOptionsExt,
  ): AsyncIterable<PageResponse>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export type ServerStreamingMethodResult<Response> = { [Symbol.asyncIterator](): AsyncIterator<Response, void> };

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
