// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v3.21.12
// source: git.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { CallContext, CallOptions } from "nice-grpc-common";
import { Empty } from "./google/protobuf/empty";

export const protobufPackage = "git.git";

export interface GitRepositoryDestroyRequest {
  id: number;
}

export interface GitRepositoryListRequest {
}

export interface GitRepositoryListResponse {
  results: GitRepositoryResponse[];
}

export interface GitRepositoryPartialUpdateRequest {
  id?: number | undefined;
  PartialUpdateFields: string[];
  name: string;
  description?: string | undefined;
  sourceUrl: string;
  sourceType?: string | undefined;
  localPath: string;
  status?: string | undefined;
  isMirror?: boolean | undefined;
  isBare?: boolean | undefined;
  defaultBranch?: string | undefined;
  lastSyncedAt?: string | undefined;
  lastCommitHash?: string | undefined;
  totalCommits?: number | undefined;
  isPublic?: boolean | undefined;
  errorMessage?: string | undefined;
  organisation: number;
  owner?: number | undefined;
}

export interface GitRepositoryRequest {
  id?: number | undefined;
  name: string;
  description?: string | undefined;
  sourceUrl: string;
  sourceType?: string | undefined;
  localPath: string;
  status?: string | undefined;
  isMirror?: boolean | undefined;
  isBare?: boolean | undefined;
  defaultBranch?: string | undefined;
  lastSyncedAt?: string | undefined;
  lastCommitHash?: string | undefined;
  totalCommits?: number | undefined;
  isPublic?: boolean | undefined;
  errorMessage?: string | undefined;
  organisation: number;
  owner?: number | undefined;
}

export interface GitRepositoryResponse {
  id?: number | undefined;
  name: string;
  description?: string | undefined;
  sourceUrl: string;
  sourceType?: string | undefined;
  localPath: string;
  status?: string | undefined;
  isMirror?: boolean | undefined;
  isBare?: boolean | undefined;
  defaultBranch?: string | undefined;
  lastSyncedAt?: string | undefined;
  lastCommitHash?: string | undefined;
  totalCommits?: number | undefined;
  isPublic?: boolean | undefined;
  createdAt?: string | undefined;
  updatedAt?: string | undefined;
  errorMessage?: string | undefined;
  organisation: number;
  owner?: number | undefined;
}

export interface GitRepositoryRetrieveRequest {
  id: number;
}

function createBaseGitRepositoryDestroyRequest(): GitRepositoryDestroyRequest {
  return { id: 0 };
}

export const GitRepositoryDestroyRequest: MessageFns<GitRepositoryDestroyRequest> = {
  encode(message: GitRepositoryDestroyRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int64(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GitRepositoryDestroyRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGitRepositoryDestroyRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GitRepositoryDestroyRequest {
    return { id: isSet(object.id) ? globalThis.Number(object.id) : 0 };
  },

  toJSON(message: GitRepositoryDestroyRequest): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GitRepositoryDestroyRequest>, I>>(base?: I): GitRepositoryDestroyRequest {
    return GitRepositoryDestroyRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GitRepositoryDestroyRequest>, I>>(object: I): GitRepositoryDestroyRequest {
    const message = createBaseGitRepositoryDestroyRequest();
    message.id = object.id ?? 0;
    return message;
  },
};

function createBaseGitRepositoryListRequest(): GitRepositoryListRequest {
  return {};
}

export const GitRepositoryListRequest: MessageFns<GitRepositoryListRequest> = {
  encode(_: GitRepositoryListRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GitRepositoryListRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGitRepositoryListRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): GitRepositoryListRequest {
    return {};
  },

  toJSON(_: GitRepositoryListRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<GitRepositoryListRequest>, I>>(base?: I): GitRepositoryListRequest {
    return GitRepositoryListRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GitRepositoryListRequest>, I>>(_: I): GitRepositoryListRequest {
    const message = createBaseGitRepositoryListRequest();
    return message;
  },
};

function createBaseGitRepositoryListResponse(): GitRepositoryListResponse {
  return { results: [] };
}

export const GitRepositoryListResponse: MessageFns<GitRepositoryListResponse> = {
  encode(message: GitRepositoryListResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.results) {
      GitRepositoryResponse.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GitRepositoryListResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGitRepositoryListResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.results.push(GitRepositoryResponse.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GitRepositoryListResponse {
    return {
      results: globalThis.Array.isArray(object?.results)
        ? object.results.map((e: any) => GitRepositoryResponse.fromJSON(e))
        : [],
    };
  },

  toJSON(message: GitRepositoryListResponse): unknown {
    const obj: any = {};
    if (message.results?.length) {
      obj.results = message.results.map((e) => GitRepositoryResponse.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GitRepositoryListResponse>, I>>(base?: I): GitRepositoryListResponse {
    return GitRepositoryListResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GitRepositoryListResponse>, I>>(object: I): GitRepositoryListResponse {
    const message = createBaseGitRepositoryListResponse();
    message.results = object.results?.map((e) => GitRepositoryResponse.fromPartial(e)) || [];
    return message;
  },
};

function createBaseGitRepositoryPartialUpdateRequest(): GitRepositoryPartialUpdateRequest {
  return {
    id: undefined,
    PartialUpdateFields: [],
    name: "",
    description: undefined,
    sourceUrl: "",
    sourceType: undefined,
    localPath: "",
    status: undefined,
    isMirror: undefined,
    isBare: undefined,
    defaultBranch: undefined,
    lastSyncedAt: undefined,
    lastCommitHash: undefined,
    totalCommits: undefined,
    isPublic: undefined,
    errorMessage: undefined,
    organisation: 0,
    owner: undefined,
  };
}

export const GitRepositoryPartialUpdateRequest: MessageFns<GitRepositoryPartialUpdateRequest> = {
  encode(message: GitRepositoryPartialUpdateRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== undefined) {
      writer.uint32(8).int64(message.id);
    }
    for (const v of message.PartialUpdateFields) {
      writer.uint32(18).string(v!);
    }
    if (message.name !== "") {
      writer.uint32(26).string(message.name);
    }
    if (message.description !== undefined) {
      writer.uint32(34).string(message.description);
    }
    if (message.sourceUrl !== "") {
      writer.uint32(42).string(message.sourceUrl);
    }
    if (message.sourceType !== undefined) {
      writer.uint32(50).string(message.sourceType);
    }
    if (message.localPath !== "") {
      writer.uint32(58).string(message.localPath);
    }
    if (message.status !== undefined) {
      writer.uint32(66).string(message.status);
    }
    if (message.isMirror !== undefined) {
      writer.uint32(72).bool(message.isMirror);
    }
    if (message.isBare !== undefined) {
      writer.uint32(80).bool(message.isBare);
    }
    if (message.defaultBranch !== undefined) {
      writer.uint32(90).string(message.defaultBranch);
    }
    if (message.lastSyncedAt !== undefined) {
      writer.uint32(98).string(message.lastSyncedAt);
    }
    if (message.lastCommitHash !== undefined) {
      writer.uint32(106).string(message.lastCommitHash);
    }
    if (message.totalCommits !== undefined) {
      writer.uint32(112).int32(message.totalCommits);
    }
    if (message.isPublic !== undefined) {
      writer.uint32(120).bool(message.isPublic);
    }
    if (message.errorMessage !== undefined) {
      writer.uint32(130).string(message.errorMessage);
    }
    if (message.organisation !== 0) {
      writer.uint32(136).int64(message.organisation);
    }
    if (message.owner !== undefined) {
      writer.uint32(144).int64(message.owner);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GitRepositoryPartialUpdateRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGitRepositoryPartialUpdateRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.PartialUpdateFields.push(reader.string());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.sourceUrl = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.sourceType = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.localPath = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.isMirror = reader.bool();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.isBare = reader.bool();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.defaultBranch = reader.string();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.lastSyncedAt = reader.string();
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.lastCommitHash = reader.string();
          continue;
        }
        case 14: {
          if (tag !== 112) {
            break;
          }

          message.totalCommits = reader.int32();
          continue;
        }
        case 15: {
          if (tag !== 120) {
            break;
          }

          message.isPublic = reader.bool();
          continue;
        }
        case 16: {
          if (tag !== 130) {
            break;
          }

          message.errorMessage = reader.string();
          continue;
        }
        case 17: {
          if (tag !== 136) {
            break;
          }

          message.organisation = longToNumber(reader.int64());
          continue;
        }
        case 18: {
          if (tag !== 144) {
            break;
          }

          message.owner = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GitRepositoryPartialUpdateRequest {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : undefined,
      PartialUpdateFields: globalThis.Array.isArray(object?.PartialUpdateFields)
        ? object.PartialUpdateFields.map((e: any) => globalThis.String(e))
        : [],
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      description: isSet(object.description) ? globalThis.String(object.description) : undefined,
      sourceUrl: isSet(object.sourceUrl) ? globalThis.String(object.sourceUrl) : "",
      sourceType: isSet(object.sourceType) ? globalThis.String(object.sourceType) : undefined,
      localPath: isSet(object.localPath) ? globalThis.String(object.localPath) : "",
      status: isSet(object.status) ? globalThis.String(object.status) : undefined,
      isMirror: isSet(object.isMirror) ? globalThis.Boolean(object.isMirror) : undefined,
      isBare: isSet(object.isBare) ? globalThis.Boolean(object.isBare) : undefined,
      defaultBranch: isSet(object.defaultBranch) ? globalThis.String(object.defaultBranch) : undefined,
      lastSyncedAt: isSet(object.lastSyncedAt) ? globalThis.String(object.lastSyncedAt) : undefined,
      lastCommitHash: isSet(object.lastCommitHash) ? globalThis.String(object.lastCommitHash) : undefined,
      totalCommits: isSet(object.totalCommits) ? globalThis.Number(object.totalCommits) : undefined,
      isPublic: isSet(object.isPublic) ? globalThis.Boolean(object.isPublic) : undefined,
      errorMessage: isSet(object.errorMessage) ? globalThis.String(object.errorMessage) : undefined,
      organisation: isSet(object.organisation) ? globalThis.Number(object.organisation) : 0,
      owner: isSet(object.owner) ? globalThis.Number(object.owner) : undefined,
    };
  },

  toJSON(message: GitRepositoryPartialUpdateRequest): unknown {
    const obj: any = {};
    if (message.id !== undefined) {
      obj.id = Math.round(message.id);
    }
    if (message.PartialUpdateFields?.length) {
      obj.PartialUpdateFields = message.PartialUpdateFields;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.description !== undefined) {
      obj.description = message.description;
    }
    if (message.sourceUrl !== "") {
      obj.sourceUrl = message.sourceUrl;
    }
    if (message.sourceType !== undefined) {
      obj.sourceType = message.sourceType;
    }
    if (message.localPath !== "") {
      obj.localPath = message.localPath;
    }
    if (message.status !== undefined) {
      obj.status = message.status;
    }
    if (message.isMirror !== undefined) {
      obj.isMirror = message.isMirror;
    }
    if (message.isBare !== undefined) {
      obj.isBare = message.isBare;
    }
    if (message.defaultBranch !== undefined) {
      obj.defaultBranch = message.defaultBranch;
    }
    if (message.lastSyncedAt !== undefined) {
      obj.lastSyncedAt = message.lastSyncedAt;
    }
    if (message.lastCommitHash !== undefined) {
      obj.lastCommitHash = message.lastCommitHash;
    }
    if (message.totalCommits !== undefined) {
      obj.totalCommits = Math.round(message.totalCommits);
    }
    if (message.isPublic !== undefined) {
      obj.isPublic = message.isPublic;
    }
    if (message.errorMessage !== undefined) {
      obj.errorMessage = message.errorMessage;
    }
    if (message.organisation !== 0) {
      obj.organisation = Math.round(message.organisation);
    }
    if (message.owner !== undefined) {
      obj.owner = Math.round(message.owner);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GitRepositoryPartialUpdateRequest>, I>>(
    base?: I,
  ): GitRepositoryPartialUpdateRequest {
    return GitRepositoryPartialUpdateRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GitRepositoryPartialUpdateRequest>, I>>(
    object: I,
  ): GitRepositoryPartialUpdateRequest {
    const message = createBaseGitRepositoryPartialUpdateRequest();
    message.id = object.id ?? undefined;
    message.PartialUpdateFields = object.PartialUpdateFields?.map((e) => e) || [];
    message.name = object.name ?? "";
    message.description = object.description ?? undefined;
    message.sourceUrl = object.sourceUrl ?? "";
    message.sourceType = object.sourceType ?? undefined;
    message.localPath = object.localPath ?? "";
    message.status = object.status ?? undefined;
    message.isMirror = object.isMirror ?? undefined;
    message.isBare = object.isBare ?? undefined;
    message.defaultBranch = object.defaultBranch ?? undefined;
    message.lastSyncedAt = object.lastSyncedAt ?? undefined;
    message.lastCommitHash = object.lastCommitHash ?? undefined;
    message.totalCommits = object.totalCommits ?? undefined;
    message.isPublic = object.isPublic ?? undefined;
    message.errorMessage = object.errorMessage ?? undefined;
    message.organisation = object.organisation ?? 0;
    message.owner = object.owner ?? undefined;
    return message;
  },
};

function createBaseGitRepositoryRequest(): GitRepositoryRequest {
  return {
    id: undefined,
    name: "",
    description: undefined,
    sourceUrl: "",
    sourceType: undefined,
    localPath: "",
    status: undefined,
    isMirror: undefined,
    isBare: undefined,
    defaultBranch: undefined,
    lastSyncedAt: undefined,
    lastCommitHash: undefined,
    totalCommits: undefined,
    isPublic: undefined,
    errorMessage: undefined,
    organisation: 0,
    owner: undefined,
  };
}

export const GitRepositoryRequest: MessageFns<GitRepositoryRequest> = {
  encode(message: GitRepositoryRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== undefined) {
      writer.uint32(8).int64(message.id);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.description !== undefined) {
      writer.uint32(26).string(message.description);
    }
    if (message.sourceUrl !== "") {
      writer.uint32(34).string(message.sourceUrl);
    }
    if (message.sourceType !== undefined) {
      writer.uint32(42).string(message.sourceType);
    }
    if (message.localPath !== "") {
      writer.uint32(50).string(message.localPath);
    }
    if (message.status !== undefined) {
      writer.uint32(58).string(message.status);
    }
    if (message.isMirror !== undefined) {
      writer.uint32(64).bool(message.isMirror);
    }
    if (message.isBare !== undefined) {
      writer.uint32(72).bool(message.isBare);
    }
    if (message.defaultBranch !== undefined) {
      writer.uint32(82).string(message.defaultBranch);
    }
    if (message.lastSyncedAt !== undefined) {
      writer.uint32(90).string(message.lastSyncedAt);
    }
    if (message.lastCommitHash !== undefined) {
      writer.uint32(98).string(message.lastCommitHash);
    }
    if (message.totalCommits !== undefined) {
      writer.uint32(104).int32(message.totalCommits);
    }
    if (message.isPublic !== undefined) {
      writer.uint32(112).bool(message.isPublic);
    }
    if (message.errorMessage !== undefined) {
      writer.uint32(122).string(message.errorMessage);
    }
    if (message.organisation !== 0) {
      writer.uint32(128).int64(message.organisation);
    }
    if (message.owner !== undefined) {
      writer.uint32(136).int64(message.owner);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GitRepositoryRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGitRepositoryRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.sourceUrl = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.sourceType = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.localPath = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.isMirror = reader.bool();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.isBare = reader.bool();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.defaultBranch = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.lastSyncedAt = reader.string();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.lastCommitHash = reader.string();
          continue;
        }
        case 13: {
          if (tag !== 104) {
            break;
          }

          message.totalCommits = reader.int32();
          continue;
        }
        case 14: {
          if (tag !== 112) {
            break;
          }

          message.isPublic = reader.bool();
          continue;
        }
        case 15: {
          if (tag !== 122) {
            break;
          }

          message.errorMessage = reader.string();
          continue;
        }
        case 16: {
          if (tag !== 128) {
            break;
          }

          message.organisation = longToNumber(reader.int64());
          continue;
        }
        case 17: {
          if (tag !== 136) {
            break;
          }

          message.owner = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GitRepositoryRequest {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : undefined,
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      description: isSet(object.description) ? globalThis.String(object.description) : undefined,
      sourceUrl: isSet(object.sourceUrl) ? globalThis.String(object.sourceUrl) : "",
      sourceType: isSet(object.sourceType) ? globalThis.String(object.sourceType) : undefined,
      localPath: isSet(object.localPath) ? globalThis.String(object.localPath) : "",
      status: isSet(object.status) ? globalThis.String(object.status) : undefined,
      isMirror: isSet(object.isMirror) ? globalThis.Boolean(object.isMirror) : undefined,
      isBare: isSet(object.isBare) ? globalThis.Boolean(object.isBare) : undefined,
      defaultBranch: isSet(object.defaultBranch) ? globalThis.String(object.defaultBranch) : undefined,
      lastSyncedAt: isSet(object.lastSyncedAt) ? globalThis.String(object.lastSyncedAt) : undefined,
      lastCommitHash: isSet(object.lastCommitHash) ? globalThis.String(object.lastCommitHash) : undefined,
      totalCommits: isSet(object.totalCommits) ? globalThis.Number(object.totalCommits) : undefined,
      isPublic: isSet(object.isPublic) ? globalThis.Boolean(object.isPublic) : undefined,
      errorMessage: isSet(object.errorMessage) ? globalThis.String(object.errorMessage) : undefined,
      organisation: isSet(object.organisation) ? globalThis.Number(object.organisation) : 0,
      owner: isSet(object.owner) ? globalThis.Number(object.owner) : undefined,
    };
  },

  toJSON(message: GitRepositoryRequest): unknown {
    const obj: any = {};
    if (message.id !== undefined) {
      obj.id = Math.round(message.id);
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.description !== undefined) {
      obj.description = message.description;
    }
    if (message.sourceUrl !== "") {
      obj.sourceUrl = message.sourceUrl;
    }
    if (message.sourceType !== undefined) {
      obj.sourceType = message.sourceType;
    }
    if (message.localPath !== "") {
      obj.localPath = message.localPath;
    }
    if (message.status !== undefined) {
      obj.status = message.status;
    }
    if (message.isMirror !== undefined) {
      obj.isMirror = message.isMirror;
    }
    if (message.isBare !== undefined) {
      obj.isBare = message.isBare;
    }
    if (message.defaultBranch !== undefined) {
      obj.defaultBranch = message.defaultBranch;
    }
    if (message.lastSyncedAt !== undefined) {
      obj.lastSyncedAt = message.lastSyncedAt;
    }
    if (message.lastCommitHash !== undefined) {
      obj.lastCommitHash = message.lastCommitHash;
    }
    if (message.totalCommits !== undefined) {
      obj.totalCommits = Math.round(message.totalCommits);
    }
    if (message.isPublic !== undefined) {
      obj.isPublic = message.isPublic;
    }
    if (message.errorMessage !== undefined) {
      obj.errorMessage = message.errorMessage;
    }
    if (message.organisation !== 0) {
      obj.organisation = Math.round(message.organisation);
    }
    if (message.owner !== undefined) {
      obj.owner = Math.round(message.owner);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GitRepositoryRequest>, I>>(base?: I): GitRepositoryRequest {
    return GitRepositoryRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GitRepositoryRequest>, I>>(object: I): GitRepositoryRequest {
    const message = createBaseGitRepositoryRequest();
    message.id = object.id ?? undefined;
    message.name = object.name ?? "";
    message.description = object.description ?? undefined;
    message.sourceUrl = object.sourceUrl ?? "";
    message.sourceType = object.sourceType ?? undefined;
    message.localPath = object.localPath ?? "";
    message.status = object.status ?? undefined;
    message.isMirror = object.isMirror ?? undefined;
    message.isBare = object.isBare ?? undefined;
    message.defaultBranch = object.defaultBranch ?? undefined;
    message.lastSyncedAt = object.lastSyncedAt ?? undefined;
    message.lastCommitHash = object.lastCommitHash ?? undefined;
    message.totalCommits = object.totalCommits ?? undefined;
    message.isPublic = object.isPublic ?? undefined;
    message.errorMessage = object.errorMessage ?? undefined;
    message.organisation = object.organisation ?? 0;
    message.owner = object.owner ?? undefined;
    return message;
  },
};

function createBaseGitRepositoryResponse(): GitRepositoryResponse {
  return {
    id: undefined,
    name: "",
    description: undefined,
    sourceUrl: "",
    sourceType: undefined,
    localPath: "",
    status: undefined,
    isMirror: undefined,
    isBare: undefined,
    defaultBranch: undefined,
    lastSyncedAt: undefined,
    lastCommitHash: undefined,
    totalCommits: undefined,
    isPublic: undefined,
    createdAt: undefined,
    updatedAt: undefined,
    errorMessage: undefined,
    organisation: 0,
    owner: undefined,
  };
}

export const GitRepositoryResponse: MessageFns<GitRepositoryResponse> = {
  encode(message: GitRepositoryResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== undefined) {
      writer.uint32(8).int64(message.id);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.description !== undefined) {
      writer.uint32(26).string(message.description);
    }
    if (message.sourceUrl !== "") {
      writer.uint32(34).string(message.sourceUrl);
    }
    if (message.sourceType !== undefined) {
      writer.uint32(42).string(message.sourceType);
    }
    if (message.localPath !== "") {
      writer.uint32(50).string(message.localPath);
    }
    if (message.status !== undefined) {
      writer.uint32(58).string(message.status);
    }
    if (message.isMirror !== undefined) {
      writer.uint32(64).bool(message.isMirror);
    }
    if (message.isBare !== undefined) {
      writer.uint32(72).bool(message.isBare);
    }
    if (message.defaultBranch !== undefined) {
      writer.uint32(82).string(message.defaultBranch);
    }
    if (message.lastSyncedAt !== undefined) {
      writer.uint32(90).string(message.lastSyncedAt);
    }
    if (message.lastCommitHash !== undefined) {
      writer.uint32(98).string(message.lastCommitHash);
    }
    if (message.totalCommits !== undefined) {
      writer.uint32(104).int32(message.totalCommits);
    }
    if (message.isPublic !== undefined) {
      writer.uint32(112).bool(message.isPublic);
    }
    if (message.createdAt !== undefined) {
      writer.uint32(122).string(message.createdAt);
    }
    if (message.updatedAt !== undefined) {
      writer.uint32(130).string(message.updatedAt);
    }
    if (message.errorMessage !== undefined) {
      writer.uint32(138).string(message.errorMessage);
    }
    if (message.organisation !== 0) {
      writer.uint32(144).int64(message.organisation);
    }
    if (message.owner !== undefined) {
      writer.uint32(152).int64(message.owner);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GitRepositoryResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGitRepositoryResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.sourceUrl = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.sourceType = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.localPath = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.isMirror = reader.bool();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.isBare = reader.bool();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.defaultBranch = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.lastSyncedAt = reader.string();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.lastCommitHash = reader.string();
          continue;
        }
        case 13: {
          if (tag !== 104) {
            break;
          }

          message.totalCommits = reader.int32();
          continue;
        }
        case 14: {
          if (tag !== 112) {
            break;
          }

          message.isPublic = reader.bool();
          continue;
        }
        case 15: {
          if (tag !== 122) {
            break;
          }

          message.createdAt = reader.string();
          continue;
        }
        case 16: {
          if (tag !== 130) {
            break;
          }

          message.updatedAt = reader.string();
          continue;
        }
        case 17: {
          if (tag !== 138) {
            break;
          }

          message.errorMessage = reader.string();
          continue;
        }
        case 18: {
          if (tag !== 144) {
            break;
          }

          message.organisation = longToNumber(reader.int64());
          continue;
        }
        case 19: {
          if (tag !== 152) {
            break;
          }

          message.owner = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GitRepositoryResponse {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : undefined,
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      description: isSet(object.description) ? globalThis.String(object.description) : undefined,
      sourceUrl: isSet(object.sourceUrl) ? globalThis.String(object.sourceUrl) : "",
      sourceType: isSet(object.sourceType) ? globalThis.String(object.sourceType) : undefined,
      localPath: isSet(object.localPath) ? globalThis.String(object.localPath) : "",
      status: isSet(object.status) ? globalThis.String(object.status) : undefined,
      isMirror: isSet(object.isMirror) ? globalThis.Boolean(object.isMirror) : undefined,
      isBare: isSet(object.isBare) ? globalThis.Boolean(object.isBare) : undefined,
      defaultBranch: isSet(object.defaultBranch) ? globalThis.String(object.defaultBranch) : undefined,
      lastSyncedAt: isSet(object.lastSyncedAt) ? globalThis.String(object.lastSyncedAt) : undefined,
      lastCommitHash: isSet(object.lastCommitHash) ? globalThis.String(object.lastCommitHash) : undefined,
      totalCommits: isSet(object.totalCommits) ? globalThis.Number(object.totalCommits) : undefined,
      isPublic: isSet(object.isPublic) ? globalThis.Boolean(object.isPublic) : undefined,
      createdAt: isSet(object.createdAt) ? globalThis.String(object.createdAt) : undefined,
      updatedAt: isSet(object.updatedAt) ? globalThis.String(object.updatedAt) : undefined,
      errorMessage: isSet(object.errorMessage) ? globalThis.String(object.errorMessage) : undefined,
      organisation: isSet(object.organisation) ? globalThis.Number(object.organisation) : 0,
      owner: isSet(object.owner) ? globalThis.Number(object.owner) : undefined,
    };
  },

  toJSON(message: GitRepositoryResponse): unknown {
    const obj: any = {};
    if (message.id !== undefined) {
      obj.id = Math.round(message.id);
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.description !== undefined) {
      obj.description = message.description;
    }
    if (message.sourceUrl !== "") {
      obj.sourceUrl = message.sourceUrl;
    }
    if (message.sourceType !== undefined) {
      obj.sourceType = message.sourceType;
    }
    if (message.localPath !== "") {
      obj.localPath = message.localPath;
    }
    if (message.status !== undefined) {
      obj.status = message.status;
    }
    if (message.isMirror !== undefined) {
      obj.isMirror = message.isMirror;
    }
    if (message.isBare !== undefined) {
      obj.isBare = message.isBare;
    }
    if (message.defaultBranch !== undefined) {
      obj.defaultBranch = message.defaultBranch;
    }
    if (message.lastSyncedAt !== undefined) {
      obj.lastSyncedAt = message.lastSyncedAt;
    }
    if (message.lastCommitHash !== undefined) {
      obj.lastCommitHash = message.lastCommitHash;
    }
    if (message.totalCommits !== undefined) {
      obj.totalCommits = Math.round(message.totalCommits);
    }
    if (message.isPublic !== undefined) {
      obj.isPublic = message.isPublic;
    }
    if (message.createdAt !== undefined) {
      obj.createdAt = message.createdAt;
    }
    if (message.updatedAt !== undefined) {
      obj.updatedAt = message.updatedAt;
    }
    if (message.errorMessage !== undefined) {
      obj.errorMessage = message.errorMessage;
    }
    if (message.organisation !== 0) {
      obj.organisation = Math.round(message.organisation);
    }
    if (message.owner !== undefined) {
      obj.owner = Math.round(message.owner);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GitRepositoryResponse>, I>>(base?: I): GitRepositoryResponse {
    return GitRepositoryResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GitRepositoryResponse>, I>>(object: I): GitRepositoryResponse {
    const message = createBaseGitRepositoryResponse();
    message.id = object.id ?? undefined;
    message.name = object.name ?? "";
    message.description = object.description ?? undefined;
    message.sourceUrl = object.sourceUrl ?? "";
    message.sourceType = object.sourceType ?? undefined;
    message.localPath = object.localPath ?? "";
    message.status = object.status ?? undefined;
    message.isMirror = object.isMirror ?? undefined;
    message.isBare = object.isBare ?? undefined;
    message.defaultBranch = object.defaultBranch ?? undefined;
    message.lastSyncedAt = object.lastSyncedAt ?? undefined;
    message.lastCommitHash = object.lastCommitHash ?? undefined;
    message.totalCommits = object.totalCommits ?? undefined;
    message.isPublic = object.isPublic ?? undefined;
    message.createdAt = object.createdAt ?? undefined;
    message.updatedAt = object.updatedAt ?? undefined;
    message.errorMessage = object.errorMessage ?? undefined;
    message.organisation = object.organisation ?? 0;
    message.owner = object.owner ?? undefined;
    return message;
  },
};

function createBaseGitRepositoryRetrieveRequest(): GitRepositoryRetrieveRequest {
  return { id: 0 };
}

export const GitRepositoryRetrieveRequest: MessageFns<GitRepositoryRetrieveRequest> = {
  encode(message: GitRepositoryRetrieveRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int64(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GitRepositoryRetrieveRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGitRepositoryRetrieveRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GitRepositoryRetrieveRequest {
    return { id: isSet(object.id) ? globalThis.Number(object.id) : 0 };
  },

  toJSON(message: GitRepositoryRetrieveRequest): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GitRepositoryRetrieveRequest>, I>>(base?: I): GitRepositoryRetrieveRequest {
    return GitRepositoryRetrieveRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GitRepositoryRetrieveRequest>, I>>(object: I): GitRepositoryRetrieveRequest {
    const message = createBaseGitRepositoryRetrieveRequest();
    message.id = object.id ?? 0;
    return message;
  },
};

export type GitRepositoryControllerDefinition = typeof GitRepositoryControllerDefinition;
export const GitRepositoryControllerDefinition = {
  name: "GitRepositoryController",
  fullName: "git.git.GitRepositoryController",
  methods: {
    create: {
      name: "Create",
      requestType: GitRepositoryRequest,
      requestStream: false,
      responseType: GitRepositoryResponse,
      responseStream: false,
      options: {},
    },
    destroy: {
      name: "Destroy",
      requestType: GitRepositoryDestroyRequest,
      requestStream: false,
      responseType: Empty,
      responseStream: false,
      options: {},
    },
    list: {
      name: "List",
      requestType: GitRepositoryListRequest,
      requestStream: false,
      responseType: GitRepositoryListResponse,
      responseStream: false,
      options: {},
    },
    partialUpdate: {
      name: "PartialUpdate",
      requestType: GitRepositoryPartialUpdateRequest,
      requestStream: false,
      responseType: GitRepositoryResponse,
      responseStream: false,
      options: {},
    },
    retrieve: {
      name: "Retrieve",
      requestType: GitRepositoryRetrieveRequest,
      requestStream: false,
      responseType: GitRepositoryResponse,
      responseStream: false,
      options: {},
    },
    update: {
      name: "Update",
      requestType: GitRepositoryRequest,
      requestStream: false,
      responseType: GitRepositoryResponse,
      responseStream: false,
      options: {},
    },
  },
} as const;

export interface GitRepositoryControllerServiceImplementation<CallContextExt = {}> {
  create(
    request: GitRepositoryRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<GitRepositoryResponse>>;
  destroy(request: GitRepositoryDestroyRequest, context: CallContext & CallContextExt): Promise<DeepPartial<Empty>>;
  list(
    request: GitRepositoryListRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<GitRepositoryListResponse>>;
  partialUpdate(
    request: GitRepositoryPartialUpdateRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<GitRepositoryResponse>>;
  retrieve(
    request: GitRepositoryRetrieveRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<GitRepositoryResponse>>;
  update(
    request: GitRepositoryRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<GitRepositoryResponse>>;
}

export interface GitRepositoryControllerClient<CallOptionsExt = {}> {
  create(
    request: DeepPartial<GitRepositoryRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<GitRepositoryResponse>;
  destroy(request: DeepPartial<GitRepositoryDestroyRequest>, options?: CallOptions & CallOptionsExt): Promise<Empty>;
  list(
    request: DeepPartial<GitRepositoryListRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<GitRepositoryListResponse>;
  partialUpdate(
    request: DeepPartial<GitRepositoryPartialUpdateRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<GitRepositoryResponse>;
  retrieve(
    request: DeepPartial<GitRepositoryRetrieveRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<GitRepositoryResponse>;
  update(
    request: DeepPartial<GitRepositoryRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<GitRepositoryResponse>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
